# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
  armhf: "ghcr.io/home-assistant/armhf-base:3.23"
  armv7: "ghcr.io/home-assistant/armv7-base:3.23"
  i386: "ghcr.io/home-assistant/i386-base:3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: LDAP Authentication Server add-on"
  org.opencontainers.image.description: "Add-on to add LDAP authentication to Home Assistant."
  org.opencontainers.image.source: "https://github.com/vqvu/home-assistant-addons/ldap-auth-server"
  org.opencontainers.image.licenses: "Apache License 2.0"
